/// Flutter icons Piccamera
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Piccamera
///      fonts:
///       - asset: fonts/Piccamera.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Piccamera {
  Piccamera._();

  static const _kFontFam = 'Piccamera';

  static const IconData camera = const IconData(0xe802, fontFamily: _kFontFam);
}
