/// Flutter icons Qrscan
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Qrscan
///      fonts:
///       - asset: fonts/Qrscan.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Qrscan {
  Qrscan._();

  static const _kFontFam = 'Qrscan';

  static const IconData qr_code = const IconData(0xe801, fontFamily: _kFontFam);
}
